### ISSUE TITLE
Calculating Regions of Interest (ROI)

### ISSUE THREAD

**Issue by fultonardo** [TranslationalBioinformaticsIGTP/CNVbenchmarkeR#2]
Greetings, 

I would like to re-create your results from Moreno-Cabrera et al. 2020 with panelcn.MOPS and DECoN using the ICR96 dataset.  From Supplementary file S12: In this dataset you have a totals of 28,875 ROIs, and 1,820 genes.  I understand that the genes are calculated from the validated file as [1,752 genes with no CNVs] + [68 genes with CNVs].  Could you help me understand how you calculate the total ROIs?

Thank you, 
-Matt

**Comment by jpuntomarcos** [comment]
Hi Matt,

The ICR96 contains 96 samples. For each sample we have the **MLPA results for certain genes or regions** (Supp File 2 in our [publication](https://www.nature.com/articles/s41431-020-0675-z)). These MLPA results overlap certain ROIs defined in the bed file (Supp File 6). Therefore, each ROI overlapping a MLPA result will be classified as TP, TN, FP or FN, depending on the tool calling results. The total number of ROIS, 28875 for the ICR96 dataset, is the sum of TPs, TNs, FPs and FNs.

Regards,
José Marcos.

**Comment by fultonardo** [comment]
Greetings José,

I see.  I wasn't expecting the FP & FN to be included.  Thank you for the clarification!!

Best wishes, 
-Matt Marshall
